[gcs]
bucket_name = "mathtestappmumbaibucket"

[gcp_service_account]
type = "service_account"
project_id = "mathtestapp"
private_key_id = "16ac464c708c94a51b6f981685afc6acdb78b717"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCiaFkrLo0sXCIz
SAdg4tk2wcOu6D39NtN+SiXP5sH+zvS7/Kf6iU1ta6EP5FBHzzvYKHB3MFKuykn9
BnI+A2idKM+LK3SvArEjnVlnfTpnOprwo3u0J6Njj/+pGKTlJWdyr7ESNjZr8SlG
btwUA+6kZlzUz48dF8rJzpAbEHuzWVIyZVuUyhD8NMpsPqWixnDfQw8elcuEXq5F
w6481FS01iBGEV9I2KJWEXxt3HHs72QpHDFMvM7f4YRLiE5sUcBcRG2g+j+Rd5M6
7Imsy6XJM3adZIRQprbF/pg7zq+ircFf8wjkYR6tFqiM+2t5cbUEMQEWvkRkm+yw
QX8nhg6tAgMBAAECggEAIT3vDHPnkP4dwPXcDsR39emEumsObyMW+IlIQozmxddK
CCVfo5wRdVVbnvNaTEx6YRTr6jWBowXETa5RWWics9hb3M5NAJpyNAo7t79N4j3A
Y4Nu6VHYs2MQzyV8cOuuSC72dTYT/xWaX3CHCvDAGrXaB/QhBLEvQI3PeL6vtyZ8
OD5hmLPoBu40WPthOG6lJtTWVYyOzAxFXd0PKkzKsbTEgmHLs0uzPT8vGuXh/4oQ
xr3YclKsfggPyNuuOuNljjRKBBPJ7ZuIiPCIUOsvyl2q4QTaVItnoy2Wc5ZjYBom
lEKR7vmxJyQT/gTv/wMbKU9rIjK523zYw5rB6LwuuQKBgQDdUahF2mO7znWkiPGt
ufFg6gawfK4QwRSzVFFWsC3oAFg7i+Ei2mVUWIOvcpvO4cl+aXfiK7yiDz0wFPkC
1Y27AvPzKbBKMwwvalBKWKAqMThJPj3FTd/Im9k5ZIbP+HtBL4eCSCi+9gBeQg22
K6cd999plDZH4pbIobuV4gRp9QKBgQC7220v7dnDiAUdZsMyIR+muTOzyJEpb02P
ZrX4lGTyaKvJbK1NfHcBndayEQEArnvLSsSZyHPaQzBc1zh5kPFPCSd7OiRi6fzV
H3qtngGqVHAyX3njplCCbs57hC+/SehTnDWb+9C0xs2iWZsKPmcdfP1+YiI6es1n
zAYaq8qG2QKBgGJH89DpVWa+HVHumlxKeV1PL59KDsZT58xnAiPb4tbm6EexK04d
6+eT0w6jd3tcmuzvCxS91WumFsb2WUof6WuFuS1fcvDQUHXx4SvSxXVXHCayZB3t
IhZk1wb8lD1gm+NrpuJ9BtMeTTWOYaZnJjRRsb2h2qT7g3gfEj1R/CHNAoGAEKdp
TKB3d8AtQ+gCUgVhuvQcQ0n6pIO7ioT+iOUO9faVlCvQSVhJbJlDmVGslxTg4Krm
NwPwUV83gGOMHCrfWbRkDaaf5yz7PyGlTJL/bsxBjhWsxqPN62JLZ+PWH807jX4B
uqxeWkhtnoD3H7dciN610mh8xFZys0sBF4g3UjECgYA91cusPfGDq5NjS56aQv30
VLh3xb2+QtjT63Y8LPamTdc6TasL9proqPLF7A4yMqBjaS+Dsm6dtlUKiVen4XTs
ubw0CKHELBwAIoKYHhDl0P+VqsFvrMHzz4iyafFH9CFBCj13lAFtR2zzKh1CqKjJ
77Av4s3TT6XX6+/b8MYPNg==
-----END PRIVATE KEY-----"""
client_email = "mathtestapp@mathtestapp.iam.gserviceaccount.com"
client_id = "109600198388740460927"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mathtestapp@mathtestapp.iam.gserviceaccount.com"
